name: Angular CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar o repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Instalar Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # usa cache automaticamente

      # Instala dependências
      - name: Install dependencies
        run: npm ci

      # Rodar testes
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # Build de produção
      - name: Build Angular
        run: npm run build -- --configuration production
